### ISSUE TITLE
[Feature Request] 支持切换夜间模式

### ISSUE THREAD

**Issue by keta1** [wu-kan/jekyll-theme-WuK#8]
能否做套夜间模式并支持切换？
晚上真的很晃眼

**Comment by wu-kan** [comment]
emm，这个主题是在 lanyon 基础上改的，原生没有夜间模式，要加夜间模式要增加很多 CSS，靠我自己的话时间不够用，而且动力也不够…可以如果有需要，这个主题也开放了自定义修改的地方，可以自己加一个 theme-base

**Comment by wu-kan** [comment]
![image](https://user-images.githubusercontent.com/44857941/160967275-19e37387-61e1-4842-aeae-74e8578380c2.png)

这个主题支持在 chrome 里自动转换成夜间模式。在 chrome 的地址栏输入 `chrome://flags`，在其中搜索 Dark 相关的选项即可。

![image](https://user-images.githubusercontent.com/44857941/160967678-988d6e58-1f01-47d4-afd0-bf33d53f216a.png)

这里我用的是 Chrome OS，不过相关选项在其他系统中也是成立的。

**Comment by wu-kan** [comment]
![Screenshot 2024-12-17 21 58 19](https://github.com/user-attachments/assets/361da4f1-fe42-4953-828c-57f33bcd5cb1)

最新的版本已经基于 [primer/css](https://github.com/primer/css) 支持深色模式。当前颜色切换跟随系统设置，也可以在 `_config.yml` 中手动指定。
